// flow-typed signature: 3443680976c2c87ebaa7b338373e9735
// flow-typed version: <<STUB>>/@shoutem/ui_v^0.10.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@shoutem/ui'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@shoutem/ui' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@shoutem/ui/components/Button' {
  declare module.exports: any;
}

declare module '@shoutem/ui/components/Card' {
  declare module.exports: any;
}

declare module '@shoutem/ui/components/Divider' {
  declare module.exports: any;
}

declare module '@shoutem/ui/components/DropDownMenu' {
  declare module.exports: any;
}

declare module '@shoutem/ui/components/GridRow' {
  declare module.exports: any;
}

declare module '@shoutem/ui/components/HorizontalPager' {
  declare module.exports: any;
}

declare module '@shoutem/ui/components/Icon/Icon' {
  declare module.exports: any;
}

declare module '@shoutem/ui/components/Icon/index' {
  declare module.exports: any;
}

declare module '@shoutem/ui/components/Image' {
  declare module.exports: any;
}

declare module '@shoutem/ui/components/ImageGallery' {
  declare module.exports: any;
}

declare module '@shoutem/ui/components/ImagePreview' {
  declare module.exports: any;
}

declare module '@shoutem/ui/components/InlineGallery' {
  declare module.exports: any;
}

declare module '@shoutem/ui/components/ListView' {
  declare module.exports: any;
}

declare module '@shoutem/ui/components/LoadingIndicator' {
  declare module.exports: any;
}

declare module '@shoutem/ui/components/NavigationBar/composeChildren' {
  declare module.exports: any;
}

declare module '@shoutem/ui/components/NavigationBar/index' {
  declare module.exports: any;
}

declare module '@shoutem/ui/components/NavigationBar/NavigationBar' {
  declare module.exports: any;
}

declare module '@shoutem/ui/components/NavigationBar/NavigationBarAnimations' {
  declare module.exports: any;
}

declare module '@shoutem/ui/components/Overlay' {
  declare module.exports: any;
}

declare module '@shoutem/ui/components/PageIndicators' {
  declare module.exports: any;
}

declare module '@shoutem/ui/components/RichMedia/createDom' {
  declare module.exports: any;
}

declare module '@shoutem/ui/components/RichMedia/HypermediaComposer' {
  declare module.exports: any;
}

declare module '@shoutem/ui/components/RichMedia/index' {
  declare module.exports: any;
}

declare module '@shoutem/ui/components/RichMedia/RichMedia' {
  declare module.exports: any;
}

declare module '@shoutem/ui/components/RichMedia/transformAnchorTag' {
  declare module.exports: any;
}

declare module '@shoutem/ui/components/RichMedia/transformHtmlTag' {
  declare module.exports: any;
}

declare module '@shoutem/ui/components/RichMedia/transformImageTag' {
  declare module.exports: any;
}

declare module '@shoutem/ui/components/RichMedia/transformVideoTag' {
  declare module.exports: any;
}

declare module '@shoutem/ui/components/Row' {
  declare module.exports: any;
}

declare module '@shoutem/ui/components/Screen' {
  declare module.exports: any;
}

declare module '@shoutem/ui/components/ScrollView/index' {
  declare module.exports: any;
}

declare module '@shoutem/ui/components/ScrollView/ScrollDriverProvider' {
  declare module.exports: any;
}

declare module '@shoutem/ui/components/ScrollView/ScrollView' {
  declare module.exports: any;
}

declare module '@shoutem/ui/components/Spinner' {
  declare module.exports: any;
}

declare module '@shoutem/ui/components/Text' {
  declare module.exports: any;
}

declare module '@shoutem/ui/components/TextInput' {
  declare module.exports: any;
}

declare module '@shoutem/ui/components/Tile' {
  declare module.exports: any;
}

declare module '@shoutem/ui/components/TouchableOpacity' {
  declare module.exports: any;
}

declare module '@shoutem/ui/components/Video/index' {
  declare module.exports: any;
}

declare module '@shoutem/ui/components/Video/Video' {
  declare module.exports: any;
}

declare module '@shoutem/ui/components/Video/VideoSourceReader' {
  declare module.exports: any;
}

declare module '@shoutem/ui/components/View' {
  declare module.exports: any;
}

declare module '@shoutem/ui/examples/components/Buttons' {
  declare module.exports: any;
}

declare module '@shoutem/ui/examples/components/Cards' {
  declare module.exports: any;
}

declare module '@shoutem/ui/examples/components/Dividers' {
  declare module.exports: any;
}

declare module '@shoutem/ui/examples/components/DropDownMenu' {
  declare module.exports: any;
}

declare module '@shoutem/ui/examples/components/Examples' {
  declare module.exports: any;
}

declare module '@shoutem/ui/examples/components/FormComponents' {
  declare module.exports: any;
}

declare module '@shoutem/ui/examples/components/Headers' {
  declare module.exports: any;
}

declare module '@shoutem/ui/examples/components/HorizontalPagers' {
  declare module.exports: any;
}

declare module '@shoutem/ui/examples/components/ImageGalleries' {
  declare module.exports: any;
}

declare module '@shoutem/ui/examples/components/Images' {
  declare module.exports: any;
}

declare module '@shoutem/ui/examples/components/index' {
  declare module.exports: any;
}

declare module '@shoutem/ui/examples/components/InlineGalleries' {
  declare module.exports: any;
}

declare module '@shoutem/ui/examples/components/NavigationBars' {
  declare module.exports: any;
}

declare module '@shoutem/ui/examples/components/Rows' {
  declare module.exports: any;
}

declare module '@shoutem/ui/examples/components/Spinners' {
  declare module.exports: any;
}

declare module '@shoutem/ui/examples/components/Stage' {
  declare module.exports: any;
}

declare module '@shoutem/ui/examples/components/Tiles' {
  declare module.exports: any;
}

declare module '@shoutem/ui/examples/components/Typography' {
  declare module.exports: any;
}

declare module '@shoutem/ui/examples/components/Videos' {
  declare module.exports: any;
}

declare module '@shoutem/ui/init' {
  declare module.exports: any;
}

declare module '@shoutem/ui/navigation/CardStack' {
  declare module.exports: any;
}

declare module '@shoutem/ui/navigation/composeChildren' {
  declare module.exports: any;
}

declare module '@shoutem/ui/navigation/index' {
  declare module.exports: any;
}

declare module '@shoutem/ui/navigation/NavigationBar' {
  declare module.exports: any;
}

declare module '@shoutem/ui/navigation/NavigationBarView' {
  declare module.exports: any;
}

declare module '@shoutem/ui/navigation/RNCardStack' {
  declare module.exports: any;
}

declare module '@shoutem/ui/navigation/SceneProvider' {
  declare module.exports: any;
}

declare module '@shoutem/ui/scripts/link' {
  declare module.exports: any;
}

declare module '@shoutem/ui/theme' {
  declare module.exports: any;
}

// Filename aliases
declare module '@shoutem/ui/components/Button.js' {
  declare module.exports: $Exports<'@shoutem/ui/components/Button'>;
}
declare module '@shoutem/ui/components/Card.js' {
  declare module.exports: $Exports<'@shoutem/ui/components/Card'>;
}
declare module '@shoutem/ui/components/Divider.js' {
  declare module.exports: $Exports<'@shoutem/ui/components/Divider'>;
}
declare module '@shoutem/ui/components/DropDownMenu.js' {
  declare module.exports: $Exports<'@shoutem/ui/components/DropDownMenu'>;
}
declare module '@shoutem/ui/components/GridRow.js' {
  declare module.exports: $Exports<'@shoutem/ui/components/GridRow'>;
}
declare module '@shoutem/ui/components/HorizontalPager.js' {
  declare module.exports: $Exports<'@shoutem/ui/components/HorizontalPager'>;
}
declare module '@shoutem/ui/components/Icon/Icon.js' {
  declare module.exports: $Exports<'@shoutem/ui/components/Icon/Icon'>;
}
declare module '@shoutem/ui/components/Icon/index.js' {
  declare module.exports: $Exports<'@shoutem/ui/components/Icon/index'>;
}
declare module '@shoutem/ui/components/Image.js' {
  declare module.exports: $Exports<'@shoutem/ui/components/Image'>;
}
declare module '@shoutem/ui/components/ImageGallery.js' {
  declare module.exports: $Exports<'@shoutem/ui/components/ImageGallery'>;
}
declare module '@shoutem/ui/components/ImagePreview.js' {
  declare module.exports: $Exports<'@shoutem/ui/components/ImagePreview'>;
}
declare module '@shoutem/ui/components/InlineGallery.js' {
  declare module.exports: $Exports<'@shoutem/ui/components/InlineGallery'>;
}
declare module '@shoutem/ui/components/ListView.js' {
  declare module.exports: $Exports<'@shoutem/ui/components/ListView'>;
}
declare module '@shoutem/ui/components/LoadingIndicator.js' {
  declare module.exports: $Exports<'@shoutem/ui/components/LoadingIndicator'>;
}
declare module '@shoutem/ui/components/NavigationBar/composeChildren.js' {
  declare module.exports: $Exports<'@shoutem/ui/components/NavigationBar/composeChildren'>;
}
declare module '@shoutem/ui/components/NavigationBar/index.js' {
  declare module.exports: $Exports<'@shoutem/ui/components/NavigationBar/index'>;
}
declare module '@shoutem/ui/components/NavigationBar/NavigationBar.js' {
  declare module.exports: $Exports<'@shoutem/ui/components/NavigationBar/NavigationBar'>;
}
declare module '@shoutem/ui/components/NavigationBar/NavigationBarAnimations.js' {
  declare module.exports: $Exports<'@shoutem/ui/components/NavigationBar/NavigationBarAnimations'>;
}
declare module '@shoutem/ui/components/Overlay.js' {
  declare module.exports: $Exports<'@shoutem/ui/components/Overlay'>;
}
declare module '@shoutem/ui/components/PageIndicators.js' {
  declare module.exports: $Exports<'@shoutem/ui/components/PageIndicators'>;
}
declare module '@shoutem/ui/components/RichMedia/createDom.js' {
  declare module.exports: $Exports<'@shoutem/ui/components/RichMedia/createDom'>;
}
declare module '@shoutem/ui/components/RichMedia/HypermediaComposer.js' {
  declare module.exports: $Exports<'@shoutem/ui/components/RichMedia/HypermediaComposer'>;
}
declare module '@shoutem/ui/components/RichMedia/index.js' {
  declare module.exports: $Exports<'@shoutem/ui/components/RichMedia/index'>;
}
declare module '@shoutem/ui/components/RichMedia/RichMedia.js' {
  declare module.exports: $Exports<'@shoutem/ui/components/RichMedia/RichMedia'>;
}
declare module '@shoutem/ui/components/RichMedia/transformAnchorTag.js' {
  declare module.exports: $Exports<'@shoutem/ui/components/RichMedia/transformAnchorTag'>;
}
declare module '@shoutem/ui/components/RichMedia/transformHtmlTag.js' {
  declare module.exports: $Exports<'@shoutem/ui/components/RichMedia/transformHtmlTag'>;
}
declare module '@shoutem/ui/components/RichMedia/transformImageTag.js' {
  declare module.exports: $Exports<'@shoutem/ui/components/RichMedia/transformImageTag'>;
}
declare module '@shoutem/ui/components/RichMedia/transformVideoTag.js' {
  declare module.exports: $Exports<'@shoutem/ui/components/RichMedia/transformVideoTag'>;
}
declare module '@shoutem/ui/components/Row.js' {
  declare module.exports: $Exports<'@shoutem/ui/components/Row'>;
}
declare module '@shoutem/ui/components/Screen.js' {
  declare module.exports: $Exports<'@shoutem/ui/components/Screen'>;
}
declare module '@shoutem/ui/components/ScrollView/index.js' {
  declare module.exports: $Exports<'@shoutem/ui/components/ScrollView/index'>;
}
declare module '@shoutem/ui/components/ScrollView/ScrollDriverProvider.js' {
  declare module.exports: $Exports<'@shoutem/ui/components/ScrollView/ScrollDriverProvider'>;
}
declare module '@shoutem/ui/components/ScrollView/ScrollView.js' {
  declare module.exports: $Exports<'@shoutem/ui/components/ScrollView/ScrollView'>;
}
declare module '@shoutem/ui/components/Spinner.js' {
  declare module.exports: $Exports<'@shoutem/ui/components/Spinner'>;
}
declare module '@shoutem/ui/components/Text.js' {
  declare module.exports: $Exports<'@shoutem/ui/components/Text'>;
}
declare module '@shoutem/ui/components/TextInput.js' {
  declare module.exports: $Exports<'@shoutem/ui/components/TextInput'>;
}
declare module '@shoutem/ui/components/Tile.js' {
  declare module.exports: $Exports<'@shoutem/ui/components/Tile'>;
}
declare module '@shoutem/ui/components/TouchableOpacity.js' {
  declare module.exports: $Exports<'@shoutem/ui/components/TouchableOpacity'>;
}
declare module '@shoutem/ui/components/Video/index.js' {
  declare module.exports: $Exports<'@shoutem/ui/components/Video/index'>;
}
declare module '@shoutem/ui/components/Video/Video.js' {
  declare module.exports: $Exports<'@shoutem/ui/components/Video/Video'>;
}
declare module '@shoutem/ui/components/Video/VideoSourceReader.js' {
  declare module.exports: $Exports<'@shoutem/ui/components/Video/VideoSourceReader'>;
}
declare module '@shoutem/ui/components/View.js' {
  declare module.exports: $Exports<'@shoutem/ui/components/View'>;
}
declare module '@shoutem/ui/examples/components/Buttons.js' {
  declare module.exports: $Exports<'@shoutem/ui/examples/components/Buttons'>;
}
declare module '@shoutem/ui/examples/components/Cards.js' {
  declare module.exports: $Exports<'@shoutem/ui/examples/components/Cards'>;
}
declare module '@shoutem/ui/examples/components/Dividers.js' {
  declare module.exports: $Exports<'@shoutem/ui/examples/components/Dividers'>;
}
declare module '@shoutem/ui/examples/components/DropDownMenu.js' {
  declare module.exports: $Exports<'@shoutem/ui/examples/components/DropDownMenu'>;
}
declare module '@shoutem/ui/examples/components/Examples.js' {
  declare module.exports: $Exports<'@shoutem/ui/examples/components/Examples'>;
}
declare module '@shoutem/ui/examples/components/FormComponents.js' {
  declare module.exports: $Exports<'@shoutem/ui/examples/components/FormComponents'>;
}
declare module '@shoutem/ui/examples/components/Headers.js' {
  declare module.exports: $Exports<'@shoutem/ui/examples/components/Headers'>;
}
declare module '@shoutem/ui/examples/components/HorizontalPagers.js' {
  declare module.exports: $Exports<'@shoutem/ui/examples/components/HorizontalPagers'>;
}
declare module '@shoutem/ui/examples/components/ImageGalleries.js' {
  declare module.exports: $Exports<'@shoutem/ui/examples/components/ImageGalleries'>;
}
declare module '@shoutem/ui/examples/components/Images.js' {
  declare module.exports: $Exports<'@shoutem/ui/examples/components/Images'>;
}
declare module '@shoutem/ui/examples/components/index.js' {
  declare module.exports: $Exports<'@shoutem/ui/examples/components/index'>;
}
declare module '@shoutem/ui/examples/components/InlineGalleries.js' {
  declare module.exports: $Exports<'@shoutem/ui/examples/components/InlineGalleries'>;
}
declare module '@shoutem/ui/examples/components/NavigationBars.js' {
  declare module.exports: $Exports<'@shoutem/ui/examples/components/NavigationBars'>;
}
declare module '@shoutem/ui/examples/components/Rows.js' {
  declare module.exports: $Exports<'@shoutem/ui/examples/components/Rows'>;
}
declare module '@shoutem/ui/examples/components/Spinners.js' {
  declare module.exports: $Exports<'@shoutem/ui/examples/components/Spinners'>;
}
declare module '@shoutem/ui/examples/components/Stage.js' {
  declare module.exports: $Exports<'@shoutem/ui/examples/components/Stage'>;
}
declare module '@shoutem/ui/examples/components/Tiles.js' {
  declare module.exports: $Exports<'@shoutem/ui/examples/components/Tiles'>;
}
declare module '@shoutem/ui/examples/components/Typography.js' {
  declare module.exports: $Exports<'@shoutem/ui/examples/components/Typography'>;
}
declare module '@shoutem/ui/examples/components/Videos.js' {
  declare module.exports: $Exports<'@shoutem/ui/examples/components/Videos'>;
}
declare module '@shoutem/ui/index' {
  declare module.exports: $Exports<'@shoutem/ui'>;
}
declare module '@shoutem/ui/index.js' {
  declare module.exports: $Exports<'@shoutem/ui'>;
}
declare module '@shoutem/ui/init.js' {
  declare module.exports: $Exports<'@shoutem/ui/init'>;
}
declare module '@shoutem/ui/navigation/CardStack.js' {
  declare module.exports: $Exports<'@shoutem/ui/navigation/CardStack'>;
}
declare module '@shoutem/ui/navigation/composeChildren.js' {
  declare module.exports: $Exports<'@shoutem/ui/navigation/composeChildren'>;
}
declare module '@shoutem/ui/navigation/index.js' {
  declare module.exports: $Exports<'@shoutem/ui/navigation/index'>;
}
declare module '@shoutem/ui/navigation/NavigationBar.js' {
  declare module.exports: $Exports<'@shoutem/ui/navigation/NavigationBar'>;
}
declare module '@shoutem/ui/navigation/NavigationBarView.js' {
  declare module.exports: $Exports<'@shoutem/ui/navigation/NavigationBarView'>;
}
declare module '@shoutem/ui/navigation/RNCardStack.js' {
  declare module.exports: $Exports<'@shoutem/ui/navigation/RNCardStack'>;
}
declare module '@shoutem/ui/navigation/SceneProvider.js' {
  declare module.exports: $Exports<'@shoutem/ui/navigation/SceneProvider'>;
}
declare module '@shoutem/ui/scripts/link.js' {
  declare module.exports: $Exports<'@shoutem/ui/scripts/link'>;
}
declare module '@shoutem/ui/theme.js' {
  declare module.exports: $Exports<'@shoutem/ui/theme'>;
}
