// flow-typed signature: ba71a8ef05482b01efb7c603466beb01
// flow-typed version: <<STUB>>/cheerio-without-node-native_v^0.20.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cheerio-without-node-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'cheerio-without-node-native' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cheerio-without-node-native/lib/api/attributes' {
  declare module.exports: any;
}

declare module 'cheerio-without-node-native/lib/api/css' {
  declare module.exports: any;
}

declare module 'cheerio-without-node-native/lib/api/forms' {
  declare module.exports: any;
}

declare module 'cheerio-without-node-native/lib/api/manipulation' {
  declare module.exports: any;
}

declare module 'cheerio-without-node-native/lib/api/traversing' {
  declare module.exports: any;
}

declare module 'cheerio-without-node-native/lib/cheerio' {
  declare module.exports: any;
}

declare module 'cheerio-without-node-native/lib/parse' {
  declare module.exports: any;
}

declare module 'cheerio-without-node-native/lib/static' {
  declare module.exports: any;
}

declare module 'cheerio-without-node-native/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cheerio-without-node-native/index' {
  declare module.exports: $Exports<'cheerio-without-node-native'>;
}
declare module 'cheerio-without-node-native/index.js' {
  declare module.exports: $Exports<'cheerio-without-node-native'>;
}
declare module 'cheerio-without-node-native/lib/api/attributes.js' {
  declare module.exports: $Exports<'cheerio-without-node-native/lib/api/attributes'>;
}
declare module 'cheerio-without-node-native/lib/api/css.js' {
  declare module.exports: $Exports<'cheerio-without-node-native/lib/api/css'>;
}
declare module 'cheerio-without-node-native/lib/api/forms.js' {
  declare module.exports: $Exports<'cheerio-without-node-native/lib/api/forms'>;
}
declare module 'cheerio-without-node-native/lib/api/manipulation.js' {
  declare module.exports: $Exports<'cheerio-without-node-native/lib/api/manipulation'>;
}
declare module 'cheerio-without-node-native/lib/api/traversing.js' {
  declare module.exports: $Exports<'cheerio-without-node-native/lib/api/traversing'>;
}
declare module 'cheerio-without-node-native/lib/cheerio.js' {
  declare module.exports: $Exports<'cheerio-without-node-native/lib/cheerio'>;
}
declare module 'cheerio-without-node-native/lib/parse.js' {
  declare module.exports: $Exports<'cheerio-without-node-native/lib/parse'>;
}
declare module 'cheerio-without-node-native/lib/static.js' {
  declare module.exports: $Exports<'cheerio-without-node-native/lib/static'>;
}
declare module 'cheerio-without-node-native/lib/utils.js' {
  declare module.exports: $Exports<'cheerio-without-node-native/lib/utils'>;
}
