// flow-typed signature: e2f71985beeef71a06dd3459045764be
// flow-typed version: <<STUB>>/moment.distance_v^1.0.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'moment.distance'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'moment.distance' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'moment.distance/dist/moment.distance' {
  declare module.exports: any;
}

declare module 'moment.distance/dist/moment.distance.min' {
  declare module.exports: any;
}

declare module 'moment.distance/lib/moment.distance' {
  declare module.exports: any;
}

declare module 'moment.distance/test/moment.distance' {
  declare module.exports: any;
}

// Filename aliases
declare module 'moment.distance/dist/moment.distance.js' {
  declare module.exports: $Exports<'moment.distance/dist/moment.distance'>;
}
declare module 'moment.distance/dist/moment.distance.min.js' {
  declare module.exports: $Exports<'moment.distance/dist/moment.distance.min'>;
}
declare module 'moment.distance/lib/moment.distance.js' {
  declare module.exports: $Exports<'moment.distance/lib/moment.distance'>;
}
declare module 'moment.distance/test/moment.distance.js' {
  declare module.exports: $Exports<'moment.distance/test/moment.distance'>;
}
