// flow-typed signature: df07f47faefb7039b8eaf4ad3e8f0580
// flow-typed version: <<STUB>>/react-native-orientation_vgit+https://github.com/yamill/react-native-orientation.git#2782917

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-orientation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-orientation' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-orientation/demo/index.android' {
  declare module.exports: any;
}

declare module 'react-native-orientation/demo/index.ios' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-orientation/demo/index.android.js' {
  declare module.exports: $Exports<'react-native-orientation/demo/index.android'>;
}
declare module 'react-native-orientation/demo/index.ios.js' {
  declare module.exports: $Exports<'react-native-orientation/demo/index.ios'>;
}
declare module 'react-native-orientation/index' {
  declare module.exports: $Exports<'react-native-orientation'>;
}
declare module 'react-native-orientation/index.js' {
  declare module.exports: $Exports<'react-native-orientation'>;
}
