// flow-typed signature: eb5cb14b0d61fc00475b31fb06c1a5a2
// flow-typed version: <<STUB>>/react-native-restart_v^0.0.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-restart'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-restart' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-restart/index' {
  declare module.exports: $Exports<'react-native-restart'>;
}
declare module 'react-native-restart/index.js' {
  declare module.exports: $Exports<'react-native-restart'>;
}
